<a href="https://colab.research.google.com/github/HammadN98/pytorch/blob/main/00_pytorch_fundamentals_exercisios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7, 7)
tensor

tensor([[0.6849, 0.5820, 0.4298, 0.2710, 0.7809, 0.5126, 0.6134],
        [0.9187, 0.9366, 0.8892, 0.9810, 0.4099, 0.1125, 0.2111],
        [0.4542, 0.9782, 0.3798, 0.2199, 0.0262, 0.8046, 0.8937],
        [0.7150, 0.9722, 0.8713, 0.3323, 0.4329, 0.6972, 0.2884],
        [0.1530, 0.5609, 0.5382, 0.8935, 0.1386, 0.0598, 0.3780],
        [0.8769, 0.1187, 0.8564, 0.8717, 0.3099, 0.1792, 0.2298],
        [0.5097, 0.0526, 0.3574, 0.2571, 0.3270, 0.3994, 0.6340]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [57]:
# Create another random tensor
tensort = torch.rand(1, 7)
tensort = tensort.T
# Perform matrix multiplication
torch.matmul(tensor, tensort)

tensor([[2.0590],
        [2.1339],
        [2.0261],
        [2.1164],
        [1.1341],
        [1.6084],
        [1.3661]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [59]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor2 = torch.rand(7, 7)
tensort2 = torch.rand(1, 7).T

# Matrix multiply tensors
tensor_mul = torch.matmul(tensor2, tensort2)
tensor_mul

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [15]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [27]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
# do Prof tensor_B = torch.rand(size=(2,3)).to(device)
cuda1 = torch.rand([2, 3], device=device)
cuda2 = torch.rand([2, 3], device=device)
cuda1.device, cuda2.device
cuda1 * cuda2
#cuda1.cuda()

tensor([[0.0015, 0.1881, 0.1751],
        [0.1215, 0.0457, 0.3945]])


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [54]:
# Perform matmul on tensor_A and tensor_B
cuda1t = cuda1.T
cuda_matmul = torch.matmul(cuda1, cuda1.T)
cuda_matmul

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

### 8. Find the maximum and minimum values of the output of 7.

In [55]:
# Find max
max = torch.max(cuda_matmul)
# Find min
min = cuda_matmul.min()
min, max

(tensor(0.2161), tensor(0.6287))

### 9. Find the maximum and minimum index values of the output of 7.

In [56]:
# Find arg max
argmax = cuda_matmul.argmax()

# Find arg min
argmin = cuda_matmul.argmin()
argmin, argmax

(tensor(1), tensor(3))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [53]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tosqueeze = torch.rand([1, 1, 1, 10])

# Remove single dimensions
squeeze = torch.squeeze(tosqueeze)

# Print out tensors and their shapes
#tosqueeze, squeeze
print(f"Tensor com dimensoes 1: {tosqueeze}, com o shape: {tosqueeze.shape}")
print('\n')
print(f"Tensor sem dimensoes 1: {squeeze}, com o shape: {squeeze.shape}")

Tensor com dimensoes 1: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), com o shape: torch.Size([1, 1, 1, 10])


Tensor sem dimensoes 1: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), com o shape: torch.Size([10])
