<a href="https://colab.research.google.com/github/HammadN98/pytorch/blob/main/00_pytorch_fundamentos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
device = 'cuda' if torch.cuda.is_available() else "cpu"

2.3.0+cu121


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# TRansformando o tensor em int de volta
scalar.item()

7

In [ ]:
vector = torch.tensor([7,1])
vector

tensor([7, 1])

In [ ]:
vector.ndim

1

In [ ]:
MATRIX = torch.tensor([[7,1],
                       [6, 2]])
MATRIX

tensor([[7, 1],
        [6, 2]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([6, 2])

In [ ]:
TENSOR0 = torch.tensor([[[[1,2,3],
                          [4,5,6],
                          [7,8,9]]]])
TENSOR0

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [ ]:
TENSOR0.ndim

4

In [ ]:
TENSOR0.shape

torch.Size([1, 1, 3, 3])

In [ ]:
TENSOR0[0]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR0[0,0,1,2] + TENSOR0[0,0,2,2]

tensor(15)

In [ ]:
TENSOR2 = torch.tensor(
    [
        [
            [
                [
        [1,2,1,1],
        [5,6,2,2],
        [3,4,3,8],
        [7,8,4,7],
                ]
            ]
        ]
    ]
)

In [ ]:
TENSOR2.ndim

5

In [ ]:
TENSOR2.shape

torch.Size([1, 1, 1, 4, 4])

In [ ]:
TENSOR2[0,0,0,2,3]

tensor(8)

In [ ]:
rand_tensor = torch.rand(2,4,3)
rand_tensor


tensor([[[0.8288, 0.6411, 0.5848],
         [0.2354, 0.8352, 0.1740],
         [0.3616, 0.5712, 0.9036],
         [0.1174, 0.4822, 0.7696]],

        [[0.6223, 0.8069, 0.7054],
         [0.3660, 0.6704, 0.7742],
         [0.9538, 0.2994, 0.1229],
         [0.9745, 0.8740, 0.4183]]])

In [ ]:
TENSOR3 = torch.tensor([[
    [[3,4],
     [4,5],
     [0,1]],

    [[8,7],
     [9,8],
     [2,3]]

    ]])
TENSOR3

tensor([[[[3, 4],
          [4, 5],
          [0, 1]],

         [[8, 7],
          [9, 8],
          [2, 3]]]])

In [ ]:
TENSOR3.ndim

4

In [ ]:
TENSOR3.shape

torch.Size([1, 2, 3, 2])

In [ ]:
rand_tensor10 = torch.rand(10,10,10)
rand_tensor10.ndim

3

In [ ]:
#Crinado um tensor com o range de imagens, 3 canais de cores, 244 pixeis de altura e largura
rand_image_size = torch.rand(size=(3,244,244))
rand_image_size

tensor([[[0.4578, 0.0415, 0.2965,  ..., 0.4062, 0.7111, 0.3389],
         [0.7213, 0.5777, 0.5525,  ..., 0.5786, 0.2895, 0.5036],
         [0.0776, 0.1823, 0.2287,  ..., 0.4009, 0.0035, 0.7810],
         ...,
         [0.5766, 0.8210, 0.2672,  ..., 0.7804, 0.6773, 0.0911],
         [0.2309, 0.6665, 0.7904,  ..., 0.6513, 0.5755, 0.1116],
         [0.4623, 0.6030, 0.4966,  ..., 0.0841, 0.4048, 0.5457]],

        [[0.1487, 0.7673, 0.6161,  ..., 0.5883, 0.4891, 0.2263],
         [0.2676, 0.3936, 0.5029,  ..., 0.6724, 0.0045, 0.0832],
         [0.5862, 0.7041, 0.0306,  ..., 0.5338, 0.0216, 0.8955],
         ...,
         [0.9246, 0.8141, 0.9064,  ..., 0.9436, 0.0597, 0.9060],
         [0.8853, 0.2720, 0.1380,  ..., 0.8071, 0.7078, 0.7338],
         [0.8176, 0.8530, 0.9123,  ..., 0.5352, 0.0569, 0.3446]],

        [[0.8398, 0.6888, 0.5771,  ..., 0.3335, 0.2900, 0.9016],
         [0.7509, 0.3786, 0.0164,  ..., 0.3425, 0.2228, 0.7554],
         [0.7214, 0.3263, 0.9877,  ..., 0.6928, 0.4824, 0.

In [ ]:
#Criando um tensor nas dimensoes do input, porem com apenas zeros
babaiaga = torch.zeros_like(input=rand_image_size)
babaiaga

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
uns = torch.ones(size=(1,4,2,2))
uns.ndim

4

In [ ]:
uns2 = torch.ones(size=(2,1,4,2,2))
uns2.ndim

5

In [ ]:
uns2

tensor([[[[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]]],



        [[[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]]]])

# Criando Tensor arange() e _like(input=)

In [ ]:
#Basicamnete como a funcao range() mas com tensor
zeronove = torch.arange(0, 10)
zeronove

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Criando um tensor nas dimensoes do input, porem com apenas zeros
comozeronove = torch.zeros_like(input=zeronove)
comozeronove

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
'''tensorumnove = torch.tensor= [[[1,2,0],
                              [0,3,2],
                              [2,0,3]]]

tensorzeroslike = torch.zeros_like(input=tensorumnove)
multi_tensor = tensorzeroslike * tensorumnove
multi_tensor'''

'tensorumnove = torch.tensor= [[[1,2,0],\n                              [0,3,2],\n                              [2,0,3]]]\n\ntensorzeroslike = torch.zeros_like(input=tensorumnove)\nmulti_tensor = tensorzeroslike * tensorumnove\nmulti_tensor'

#tipos de dados tensor

In [ ]:
#Float 32 Tensor
float_32_TENSOR = torch.tensor([3, 6, 7],
                               dtype=None, # Tipo de dados
                               device=None, # CPU ou CUDA
                               requires_grad=False) # Rastrear ou nao o gradinete das operacoes com o tensor
float_32_TENSOR

tensor([3, 6, 7])

In [ ]:
float_32_TENSOR.dtype

torch.int64

In [ ]:
float_16_TENSOR = float_32_TENSOR.type(torch.float16)
float_16_TENSOR

tensor([3., 6., 7.], dtype=torch.float16)

In [ ]:
float64 = torch.rand(size=(1,4,2), dtype=torch.float64)
float64

tensor([[[0.2473, 0.7481],
         [0.2187, 0.9595],
         [0.6138, 0.6829],
         [0.6074, 0.2673]]], dtype=torch.float64)

In [ ]:
float_16_TENSOR2 = float64.type(torch.float16)
float_16_TENSOR2

tensor([[[0.2473, 0.7480],
         [0.2188, 0.9595],
         [0.6138, 0.6831],
         [0.6074, 0.2673]]], dtype=torch.float16)

In [ ]:
int_32_TENSOR = torch.tensor([3, 6, 7],
                               dtype=torch.int32, # Tipo de dados
                               device=None, # CPU ou CUDA
                               requires_grad=False) # Rastrear ou nao o gradinete das operacoes com o tensor
int_32_TENSOR

tensor([3, 6, 7], dtype=torch.int32)

In [ ]:
float_32_TENSOR *int_32_TENSOR

tensor([ 9, 36, 49])

In [ ]:
# Pegando informacoes do tensor
informacoes_tensor = torch.rand(3,4)
print(informacoes_tensor)
print(f"Shape do tensor:  {informacoes_tensor.shape}")
print(f"Tipo de dados do tensor: {informacoes_tensor.dtype}")
print(f"Dispositivo do tensor: {informacoes_tensor.device}")

tensor([[0.9661, 0.8139, 0.6702, 0.4379],
        [0.3602, 0.7612, 0.2260, 0.4817],
        [0.5591, 0.6752, 0.8147, 0.2420]])
Shape do tensor:  torch.Size([3, 4])
Tipo de dados do tensor: torch.float32
Dispositivo do tensor: cpu


In [ ]:
int_32_TENSOR2 = torch.tensor([3, 6, 7],
                               dtype=torch.int32, # Tipo de dados
                               device=device, # 'cpu' ou 'cuda'
                               requires_grad=False) # Rastrear ou nao o gradinete das operacoes com o tensor
int_32_TENSOR2

tensor([3, 6, 7], dtype=torch.int32)

### Manipulacao de Tensor (operacoes)

Operacoes de Tensor
* Adicao
* Subtracao
* Multiplicacao (todos a por todos b)
* Multiplicacao de matrix                                       


In [ ]:
# Somando 10
tensor_op = torch.tensor([1, 2, 3])
tensor_op + 10

tensor([11, 12, 13])

In [ ]:
# Subtraindo 10
tensor_op - 10

tensor([-9, -8, -7])

In [ ]:
# Multiplicando 10
tensor_op * 10

tensor([10, 20, 30])

In [ ]:
torch.mul(tensor_op, 100)

tensor([100, 200, 300])

In [ ]:
torch.add(tensor_op, 100)

tensor([101, 102, 103])

In [ ]:
torch.sub(tensor_op, 100)

tensor([-99, -98, -97])

# Multiplicacao de Matriz

###Element-wise(numero pelo matriz)
### Matriz por Matriz(dot product)

In [ ]:
print(tensor_op, '*' ,tensor_op)
print(f"Igual a {tensor_op * tensor_op}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Igual a tensor([1, 4, 9])


In [ ]:
mum = torch.tensor([[1 ,2 ,3],
                   [4, 5, 6]])
mdois = torch.tensor([[7, 8],
                     [9, 10],
                     [11, 12]])

In [ ]:
torch.matmul(mum, mdois)

tensor([[ 58,  64],
        [139, 154]])

In [ ]:
torch.matmul(tensor_op, tensor_op)

tensor(14)

In [ ]:
tensor_time = torch.rand(19, 90)

tensor_time2 = torch.rand(90, 19)


In [ ]:
%%time
value = 0
for i in range(len(tensor_time)):
  value += tensor_time[i] * tensor_time[i]
print(value)

tensor([5.9591, 4.7445, 8.0264, 6.7418, 6.9179, 6.0974, 4.7027, 6.1977, 7.1018,
        6.3360, 6.4655, 5.4333, 6.6125, 6.5898, 4.5694, 7.3572, 6.5656, 5.9667,
        7.4261, 6.7236, 6.3206, 5.3691, 5.4473, 7.5144, 6.3236, 7.1386, 7.7643,
        6.1189, 7.4064, 8.3847, 4.2541, 3.2245, 5.4728, 5.6055, 6.5668, 6.8892,
        3.9204, 6.4278, 5.6609, 8.7449, 5.8123, 7.6557, 5.0260, 4.9023, 5.9473,
        6.8257, 7.2918, 5.6422, 8.2126, 5.0855, 6.4562, 6.8802, 6.4623, 7.0353,
        8.1802, 6.8509, 5.3779, 6.8243, 7.5024, 5.3549, 5.5188, 4.3557, 3.7429,
        5.4425, 5.9451, 7.2033, 6.4475, 6.7937, 7.0039, 7.1662, 5.2925, 7.8449,
        8.9390, 5.7332, 8.2867, 5.5835, 7.1679, 8.2729, 6.0248, 5.4596, 6.7408,
        4.0207, 6.9761, 5.4283, 5.9333, 7.5273, 6.0091, 5.2761, 6.0169, 6.9688])
CPU times: user 5.02 ms, sys: 0 ns, total: 5.02 ms
Wall time: 7.97 ms


In [ ]:
%%time
torch.matmul(tensor_time, tensor_time2)
#Ver no chat mxn X nxp -> mxp

CPU times: user 754 µs, sys: 0 ns, total: 754 µs
Wall time: 7.49 ms


tensor([[24.8347, 22.5758, 22.5556, 22.7822, 23.7317, 24.7048, 19.7732, 21.5461,
         24.3404, 23.3131, 22.5057, 23.4701, 26.4961, 24.2108, 27.2561, 23.7933,
         23.2722, 25.1889, 26.0953],
        [23.6763, 22.8798, 20.8156, 21.5771, 22.1245, 22.1784, 18.2308, 20.4431,
         22.5510, 22.8129, 21.8058, 21.1847, 25.2372, 21.0398, 25.0441, 22.3500,
         19.8763, 23.8170, 23.9071],
        [22.1535, 22.3078, 20.7748, 20.6474, 20.2290, 21.1533, 17.3601, 18.7413,
         21.7813, 21.6665, 19.2592, 20.8844, 23.8365, 21.8782, 25.5265, 20.9237,
         17.8352, 22.5287, 22.1039],
        [25.1833, 22.7964, 21.8029, 21.6543, 23.3938, 21.5759, 18.7007, 22.5016,
         24.2195, 22.9397, 22.2793, 22.7361, 25.2166, 22.8476, 27.3714, 23.2009,
         19.7285, 24.3327, 24.8797],
        [22.1587, 20.2841, 19.5937, 19.6504, 21.5659, 20.5636, 16.1431, 18.6180,
         19.5664, 21.1445, 18.5257, 20.5404, 22.0541, 20.5392, 22.9070, 19.8810,
         17.9139, 20.8009, 20.9681],
     

### Erros de shape (Multiplicacao de Matriz)

#### Duas regras basicas
* Elemento X Matriz (element-wise)
* Matriz X Matriz (dot Product)

#### Para Matriz X Matriz

Duas regras devem ser satisfeitas

* As **dimensoes de dentro** devem ser iguais:

  * (3, 2) @ (3, 2) -> Nao funciona
  * (3, 2) @ (2, 3) -> funciona
  * (2, 3) @ (3, 2) -> funciona

* O resultado se dara pelas **dimensoes de fora**:

  * (3, 2) @ (2, 3) -> (3, 3)
  * (2, 3) @ (3, 2) -> (2, 2)

Transposicao

In [ ]:
mum

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#Da erro pois as duas tem o mesmo fortamo, e nao obedecem a regra de as dimensoes do meio serem iguais
#torch.matmul(mum, mum)

In [ ]:
#para resolver, se deve transpor uma das matrizes (torch.T)
mum.T


tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [ ]:
torch.matmul(mum, mum.T)

tensor([[14, 32],
        [32, 77]])

In [ ]:
print(f" {mum} \n \n {mum.T}")

 tensor([[1, 2, 3],
        [4, 5, 6]]) 
 
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
print(f"Shape original: mum = {mum.shape}\n")
print(f"Para multiplicar eles {mum.shape}, por ele mesmo e necessario transpor {mum.T.shape}\n")
print(f"Multiplicando: {mum} \n@\n {mum.T} <- As dimensoes de dentro agora sao iguais\n")
print("Resultado: \n")
resultado = torch.matmul(mum, mum.T)
print(resultado)
print(f"\n Shape da saida: {resultado.shape} a saida fica com o tamanho das dimensoes de fora ")

Shape original: mum = torch.Size([2, 3])

Para multiplicar eles torch.Size([2, 3]), por ele mesmo e necessario transpor torch.Size([3, 2])

Multiplicando: tensor([[1, 2, 3],
        [4, 5, 6]]) 
@
 tensor([[1, 4],
        [2, 5],
        [3, 6]]) <- As dimensoes de dentro agora sao iguais

Resultado: 

tensor([[14, 32],
        [32, 77]])

 Shape da saida: torch.Size([2, 2]) a saida fica com o tamanho das dimensoes de fora 


### Tensor Aggregation

In [ ]:
resultado.max(), resultado.min(), resultado.sum(), #resultado.mean()

(tensor(77), tensor(14), tensor(155))

In [ ]:
torch.mean(resultado.type(torch.float32))

tensor(38.7500)

In [ ]:
resultado32 = resultado.type(torch.float32)
resultado32.mean()

tensor(38.7500)

In [ ]:
mum

tensor([[1, 2, 3],
        [4, 5, 6]])

### Encontrando pasicao maxima e minima no tensor

- argmin()
- argmax()

In [ ]:
mum.argmin()

tensor(0)

In [ ]:
mum[0]

tensor([1, 2, 3])

In [ ]:
argtensor = torch.rand(3,4)
argtensor


tensor([[0.7176, 0.5409, 0.3900, 0.3815],
        [0.0287, 0.4672, 0.5729, 0.4801],
        [0.1486, 0.8478, 0.6506, 0.8858]])

In [ ]:
argtensor.argmin(), mum.argmax()

(tensor(4), tensor(5))

In [ ]:
argtensor[0:, :2]

tensor([[0.7176, 0.5409],
        [0.0287, 0.4672],
        [0.1486, 0.8478]])

### Reshaping

In [ ]:
tensorx = torch.arange(1, 10)
tensorx, tensorx.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
tensorx2 = torch.arange(11, 20)
tensorx2, tensorx2.shape

(tensor([11, 12, 13, 14, 15, 16, 17, 18, 19]), torch.Size([9]))

In [ ]:
tensorx.reshape(3, 3), tensorx.reshape(3, 3).shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

### View

In [ ]:
tensor_view = tensorx.view(9, 1)
tensor_view, tensor_view.view(9, 1).shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
tensor_view, tensorx

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
tensor_view[0: 1] = 7

In [ ]:
#AO atribuir um valor diferente para o tensor_view, o mesmo ocorre com o tensor original, pois os dois compartilha a mesma memoria
tensor_view, tensorx

(tensor([[7],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 tensor([7, 2, 3, 4, 5, 6, 7, 8, 9]))

### Stack

In [ ]:
tensor_stack = torch.stack([tensorx, tensorx2], dim=0)
tensor_stack, tensor_stack.shape

(tensor([[ 7,  2,  3,  4,  5,  6,  7,  8,  9],
         [11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 torch.Size([2, 9]))

In [ ]:
tensor_stack2 = torch.stack([tensorx, tensorx2], dim=1)
tensor_stack2, tensor_stack2.shape

(tensor([[ 7, 11],
         [ 2, 12],
         [ 3, 13],
         [ 4, 14],
         [ 5, 15],
         [ 6, 16],
         [ 7, 17],
         [ 8, 18],
         [ 9, 19]]),
 torch.Size([9, 2]))

### Squeeze

In [ ]:
tensorxx = torch.squeeze(tensorx)
tensorxx

tensor([7, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# REmove todas as dimensoes simples do tensor, dimensoes simples sao 1
tensorx.shape

torch.Size([9])

In [ ]:
tensorx

tensor([7, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# adicionando uma diemnsao 1 para poder tirar, eh mole tmnc
tensorxxx = torch.unsqueeze(tensorx, dim=0)
tensorxxx

tensor([[7, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
#torch.squeeze() - remove todas as diemnsoes 1 do tensor
print(f"Tensor inicial: {tensorxxx}")
print(f"Shape inicial: {tensorxxx.shape}")
print("\n \n")
# Removendo as dimensoes do tensorxxx
tensor_esq = torch.squeeze(tensorxxx)
print(f"Tensor final: {tensor_esq}")
print(f"Shape Final: {tensor_esq.shape}")

Tensor inicial: tensor([[7, 2, 3, 4, 5, 6, 7, 8, 9]])
Shape inicial: torch.Size([1, 9])

 

Tensor final: tensor([7, 2, 3, 4, 5, 6, 7, 8, 9])
Shape Final: torch.Size([9])


In [ ]:
tensorxxx2 =torch.tensor([[[[1,2,3],
                            [4,5,6],
                            [7,8,9]]]])
tensorxxx2, tensorxxx2.shape

(tensor([[[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]]]),
 torch.Size([1, 1, 3, 3]))

In [ ]:
tensor_squeezed = torch.squeeze(tensorxxx2)
print(f"{tensor_squeezed} \n {tensor_squeezed.shape}")

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 
 torch.Size([3, 3])


In [ ]:
print(f"{tensorxxx2.ndim} \n{torch.squeeze(tensorxxx2).ndim}")

4 
2


###Unsqueeze

In [ ]:
# torch.unsqueeze() - Adiciona uma 1 dimensao, na dim espeficica(dim=0 no elemento 0, dim=-1 no ultimo elemento, e o resto)
tensor_unsq = torch.unsqueeze(tensorxxx2, dim=3)
tensor_unsq, tensor_unsq.shape

(tensor([[[[[1, 2, 3]],
 
           [[4, 5, 6]],
 
           [[7, 8, 9]]]]]),
 torch.Size([1, 1, 3, 1, 3]))

In [ ]:
tensor_squeezed, tensor_unsq

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[[[[1, 2, 3]],
 
           [[4, 5, 6]],
 
           [[7, 8, 9]]]]]))

In [ ]:
tensor_unsq3 = tensor_squeezed.unsqueeze(dim=0)
tensor_unsq3

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
print(f"Tensor Inicial: {tensor_squeezed}")
print(f"Shape Inicial: {tensor_squeezed.shape}\n\n")

#Adicionando uma dimensao 1, na dimensao 0 do tensor
print(f"Tensor Final: {tensor_unsq3}")
print(f"Shape Final: {tensor_unsq3.shape}")

Tensor Inicial: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Shape Inicial: torch.Size([3, 3])


Tensor Final: tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Shape Final: torch.Size([1, 3, 3])


### Permute

In [ ]:
#torch.permute - aruma as dimensoes do tensor em uma ordem especifica
x_original = torch.rand(size=(244, 244, 3)) #Altura, LArgura, RGB

#Alterando a ordem das dimensoes
x_permuted = x_original.permute(2, 0, 1) #Mudando os axis 0->1, 1->2, 2->0

print(f"Shape Original: {x_original.shape}")
print(f"Shape Final: {x_permuted.shape}")
print(f"{x_original[0, 0, 0,]}")

Shape Original: torch.Size([244, 244, 3])
Shape Final: torch.Size([3, 244, 244])
0.1340712308883667


In [ ]:
x_original[0, 0, 0]
original_estatico = x_original[0, 0, 0]
original_estatico, x_original[0, 0, 0]

(tensor(0.1341), tensor(0.1341))

In [ ]:
x_original[0, 0, 0] = 2

In [ ]:
x_original[0, 0, 0]

tensor(2.)

In [ ]:
x_permuted[0, 0, 0]

tensor(2.)

In [ ]:
# Essa alteracao em um fica gravado no outro pois eles ocupam o mesmo espaco de memoria, por isso nao "funciona",
# o estatico esta a apontar para a memoria do x_original logo ele tbm pega a nova atribuicao
print(f"Valor original de x_original[0, 0, 0] {original_estatico}, \nValor de x_original[0, 0, 0] apor adicionar 2: {x_original[0, 0, 0]} \nValor de x_permuted[0, 0, 0] apos a adicao: {x_permuted[0, 0, 0]}")

Valor original de x_original[0, 0, 0] 2.0, 
Valor de x_original[0, 0, 0] apor adicionar 2: 2.0 
Valor de x_permuted[0, 0, 0] apos a adicao: 2.0


In [ ]:
# Indexing (Selecionando data dos tensors)
#Igual ao usar Numpy
tensor_index = torch.arange(1, 10).reshape(1, 3, 3)
tensor_index, tensor_index.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
tensor_index[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# tensor_index[0, 0] ou
tensor_index[0][0]

tensor([1, 2, 3])

In [ ]:
tensor_index[0][0] [0]

tensor(1)

In [ ]:
tensor_index[0][1][1]

tensor(5)

In [ ]:
tensor_index[0][-1][-1]

tensor(9)

In [ ]:
# : pode ser usado para selecionar o "todo" de uma dimensao
tensor_index[0, :, 1]

tensor([2, 5, 8])

In [ ]:
tensor_index[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
tensor_index[0, 0, :]

tensor([1, 2, 3])

In [ ]:
tensor_index[0, :, 2]

tensor([3, 6, 9])

In [ ]:
tensor_index[0, 1, 2], tensor_index[0, 2, 1]

(tensor(6), tensor(8))

# Torch tensor e Numpy

*   Dados em Numpy, tranformar em Torch -> ´torch.from_numpy(ndaaray)´
*   Pytorch tensor to numpy -> ´´torch.Tensor.numpy()´´






In [ ]:
array = np.arange(1.0 ,8.0)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
tensor_numpy = torch.from_numpy(array)
tensor_numpy

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
#Array dtype originl é float64
#Do tensor o original é float32,
#este encontra-se em float64 pois foi feito apartir do Numpy Array
array.dtype, tensor_numpy.dtype

(dtype('float64'), torch.float64)

In [ ]:
#Assim alterando para trasnformar em float32. Data type issue
tensor_numpy.type(torch.float32).dtype

torch.float32

In [ ]:
#Mudar o valor no Array,
# nao ir mudar no Tensor(Pois nao tem-se uma nova atribuicao),
#logo eles nao ocupam o mesmo espaco de memoria
array = array + 1
array, tensor_numpy

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor_numpy = torch.from_numpy(array)
tensor_numpy

tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)

In [ ]:
#Tensor para Numpy
tensor_tn = torch.ones(7)
numpy_tensor = tensor_tn.numpy()
tensor_tn, numpy_tensor
# Note que aqui como o Tensor e criado em default por float32,
#ao passar para Numpy o tipo permanesce o mesmo(float32)

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
import numpy as np
import math

# Create random input and output data
x = np.linspace(-math.pi, math.pi, 2000)
y = np.sin(x)

# Randomly initialize weights
a = np.random.randn()
b = np.random.randn()
c = np.random.randn()
d = np.random.randn()

learning_rate = 1e-6
for t in range(2000):
    # Forward pass: compute predicted y
    # y = a + b x + c x^2 + d x^3
    y_pred = a + b * x + c * x ** 2 + d * x ** 3

    # Compute and print loss
    loss = np.square(y_pred - y).sum()
    if t % 100 == 99:
        print(t, loss)

    # Backprop to compute gradients of a, b, c, d with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_a = grad_y_pred.sum()
    grad_b = (grad_y_pred * x).sum()
    grad_c = (grad_y_pred * x ** 2).sum()
    grad_d = (grad_y_pred * x ** 3).sum()

    # Update weights
    a -= learning_rate * grad_a
    b -= learning_rate * grad_b
    c -= learning_rate * grad_c
    d -= learning_rate * grad_d

print(f'Result: y = {a} + {b} x + {c} x^2 + {d} x^3')

99 3312.833133323621
199 2230.0653655006863
299 1503.4239955094881
399 1015.3879519946615
499 687.3352754631616
599 466.632395149071
699 318.0190682184884
799 217.85656145706017
899 150.28526319969436
999 104.6563070755397
1099 73.81370404278339
1199 52.94458234411376
1299 38.80912902926873
1399 29.22446819644377
1499 22.71847810661159
1599 18.297412111700137
1699 15.289785524600529
1799 13.24141031536553
1899 11.844758674679
1999 10.891385580592786
Result: y = 0.03512809477700523 + 0.8264210615586609 x + -0.006060180883053593 x^2 + -0.08901766414705288 x^3


### Reprodutibilidade

Resumo do funcionamento de redes neurais:
Comece com numeros aleatorios -> realiza operacoes nos Tensor -> atualiza os valores para se parecerem mais com os dados -> de novo -> de novo -> de novo...

Para reduzir essa aleatoriadade existe o **Random Seed** que serve para deixar a aleatoridade replicavel. Ao setar um valor, um dado aleatorio sera replicavel com essa mesma seed




In [ ]:
rand_a = torch.rand(3, 4)
rand_b = torch.rand(3, 4)

print(rand_a)
print(rand_b)
print(rand_a == rand_b)

tensor([[0.2795, 0.7008, 0.9279, 0.1852],
        [0.3860, 0.9834, 0.9789, 0.3711],
        [0.0793, 0.8704, 0.7973, 0.7046]])
tensor([[0.4660, 0.8386, 0.9479, 0.2631],
        [0.4227, 0.9889, 0.5543, 0.8039],
        [0.7837, 0.9301, 0.0922, 0.0397]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
rand_c = torch.rand(3, 4)
rand_d = torch.rand(3, 4)

print(rand_c)
print(rand_d)
print(rand_c == rand_d)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
rand_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
rand_d = torch.rand(3, 4)

print(rand_c)
print(rand_d)
print(rand_c == rand_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
#Checando se tem acesso a GPU
torch.cuda.is_available()

False

In [ ]:
#Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# Count number of device
torch.cuda.device_count()

0

### Colocando Tensors/Modelos na GPU

GPU faz calculos mais rapidos

In [ ]:
#Tensor default, sem o device o default bm e cpu
tensor_cpu = torch.tensor([1, 2, 3], device="cpu")

#Nao esta na GPU
print(tensor_cpu, tensor_cpu.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Mudando o Tensor para gpu, se disponivel
tensor_gpu = tensor_cpu.to(device)
tensor_gpu

tensor([1, 2, 3])

In [ ]:
#Mudando e volta pra a cpu, Numpy so funciona na cpu(caso o problema seja com Numpy)
#tensor_gpu.numpy()
'''Nao funciona pq esta em gpu, deve-se passar para a cpu, para entao transformar um Numpy'''

'Nao funciona pq esta em gpu, deve-se passar para a cpu, para entao transformar um Numpy'

In [ ]:
#tensor_cpu_back = tensor_gpu.cpu().numpy()
#tensor_cpu_back
#OU
tensor_cpu_back = tensor_gpu.cpu()
tensor_cpu_back.numpy()

array([1, 2, 3])